name: Compile

on:
  - push
  - pull_request

jobs:
  build_gcc_linux:
    name: "Build: GCC/Linux"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # all history
          fetch-depth: 0
      - name: Fetch Tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - name: Install dependencies
        run: ./deps.py
        working-directory: .github/workflows
      - name: Add ccache to PATH
        run: echo "::add-path::/usr/lib/ccache"
      - name: Cache compilation
        uses: actions/cache@v1
        with:
          path: .
          key: gcc-crawl-crawl
          restore-keys: |
            gcc-crawl-
            gcc-
      - run: make -j$(nproc)
        working-directory: crawl-ref/source
      - run: ./crawl -builddb
        working-directory: crawl-ref/source
