name: Unit Tests
on:
  - push
  - pull_request
jobs:
  coveralls_catch2:
    name: Unit Tests (GCC/Linux) + Coveralls
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # all history
          fetch-depth: 0
      - name: Fetch Tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - name: Install dependencies
        run: ./deps.py
        working-directory: .github/workflows
      - name: Add ccache to PATH
        run: echo "::add-path::/usr/lib/ccache"
      - name: Cache compilation
        uses: actions/cache@v1
        with:
          path: /home/runner/.ccache
          key: ccache-gcc-crawl-catch2
          restore-keys: |
            ccache-gcc-crawl-catch2
            ccache-gcc-crawl-
            ccache-gcc-
      - run: make -j$(nproc) catch2-tests
        working-directory: crawl-ref/source
      - name: Install Coveralls agent
        run: sudo pip install cpp-coveralls
      - name: Run Coveralls
        run: cpp-coveralls --gcov-options '\-lp' -E '.*/rltiles/' -E '.*/levcomp\.' -E '.*/conftest\.' -E '.*/mapdef\.' -E '.*/tag-version\.h$' -E '.*/item-prop-enum\.h$'
